### ISSUE TITLE
autosuggestion support

### ISSUE THREAD

**Issue by dontdieych** [zsh-users/fizsh#7]
are you plan to support auto suggestion?

**Comment by guidovansteen** [comment]
Thanks for your suggestion. I modelled fizsh after fish version 1.23.1. If I remember correctly, this version of fish did not have autosuggestions. 

This being said, autosuggestion for zsh is currently provided by https://github.com/tarruda/zsh-autosuggestions. It seems that Tarruda's package works fine with fizsh after loading it at the end of ~/.fizsh/.fizshrc. 

I have never thought of packaging it as a part of zsh-autosuggestions, but it could be worth considering. Or at least I could provide some instructions on how to add zsh-autosuggestions in such a way that it works with fizsh.

**Comment by guidovansteen** [comment]
The main file of https://github.com/tarruda/zsh-autosuggestions is called "autosuggestions.zsh". In this file the fragment 

`ZLE_AUTOSUGGEST_COMPLETION_WIDGETS=(
complete-word expand-or-complete expand-or-complete-prefix list-choices
menu-complete reverse-menu-complete menu-expand-or-complete menu-select
accept-and-menu-complete
)` 

yields an error when autocompletion is invoked within fizsh. In fizsh `tab` is bound to the widget `_fizsh-expand-or-complete-and-highlight` (and not to `expand-or-complete` see https://github.com/zsh-users/zsh-syntax-highlighting/issues/102). 

Autocompletion seems to work when the above fragment is changed into: 

`ZLE_AUTOSUGGEST_COMPLETION_WIDGETS=(
complete-word _fizsh-expand-or-complete-and-highlight expand-or-complete-prefix list-choices
menu-complete reverse-menu-complete menu-expand-or-complete menu-select
accept-and-menu-complete
)`

**Comment by dontdieych** [comment]
Thanks for explanation. I'll give a shot.

Thanks.

**Comment by nift4** [comment]
> The main file of https://github.com/tarruda/zsh-autosuggestions is called "autosuggestions.zsh". In this file the fragment
> 
> `ZLE_AUTOSUGGEST_COMPLETION_WIDGETS=( complete-word expand-or-complete expand-or-complete-prefix list-choices menu-complete reverse-menu-complete menu-expand-or-complete menu-select accept-and-menu-complete )`
> 
> yields an error when autocompletion is invoked within fizsh. In fizsh `tab` is bound to the widget `_fizsh-expand-or-complete-and-highlight` (and not to `expand-or-complete`). This is to address [zsh-users/zsh-syntax-highlighting#102](https://github.com/zsh-users/zsh-syntax-highlighting/issues/102).
> 
> Autocompletion seems to work when the above fragment is changed into:
> 
> `ZLE_AUTOSUGGEST_COMPLETION_WIDGETS=( complete-word _fizsh-expand-or-complete-and-highlight expand-or-complete-prefix list-choices menu-complete reverse-menu-complete menu-expand-or-complete menu-select accept-and-menu-complete )`

That is now broken. Could you maybe post an new solution?
