### ISSUE TITLE
Is it possible to install a zsh theme in fizsh? If so how?

### ISSUE THREAD

**Issue by SurfaceThought** [zsh-users/fizsh#8]
Thanks!

**Comment by guidovansteen** [comment]
Fizsh's currently has only one theme, which is modelled after fish (fishshell.com). You could easily change this theme. E.g. you could just source another prompt. 

If you want to use themes, you might take a look at https://github.com/sorin-ionescu/prezto as well.

**Comment by guidovansteen** [comment]
Closing this issue.
