### ISSUE TITLE
fizsh-miscellaneous.zsh:57: no matches found: key[End]}=

### ISSUE THREAD

**Issue by pjk25** [zsh-users/fizsh#9]
`/Users/me/fizsh-miscellaneous.zsh:57: no matches found: key[End]}=` is printed when I invoke fizsh. I have fizsh installed via homebrew on OS X El Capitan.

**Comment by guidovansteen** [comment]
There seems to be something wrong with your `$key` variable. You might unset it, before invoking fizsh. Fizsh sets will automatically create it, if `$key` does not exist: 

`$ unset key` 
`$ fizsh`

Does this help?

**Comment by guidovansteen** [comment]
Closing this issue.

**Comment by pjk25** [comment]
Hi @guidovansteen, sorry for missing your comment before.  Interestingly, unset key does not solve the issue.
